// Каталог курсов. Чтобы добавить курс или поменять цену — допишите объект в массив.
// Программа курса (модули и уроки) — в course-programs.ts.
// Обложка: положите картинку в public/images/ и впишите путь в image, например '/images/art1.png'.
// Пока image пустой — на обложке иконка icon.

import type { CatalogItem } from './types';

export interface Course extends CatalogItem {
  /** Ссылка на страницу курса */
  href: string;
}

export const COURSES: Course[] = [
  {
    title: 'Рисунок с нуля',
    description:
      'Постановка руки и штриховки, контроль линий, техника скетчинга, композиция линий, градации света и тени — без художественного опыта.',
    age: 9,
    audience: ['beginners', 'kids'],
    price: 4900,
    priceNote: 'за курс',
    tone: 'peach',
    icon: '/icons/brush.svg',
    image: '/images/art1.png',
    href: '#',
  },
  {
    title: 'Маленький творец',
    description: 'Программа для детей в доступной форме: знакомство с цветами, формами и первыми техниками.',
    age: 6,
    audience: ['kids', 'beginners'],
    price: 4600,
    priceNote: 'за курс',
    tone: 'cream',
    icon: '/icons/point.svg',
    image: '',
    href: '#',
  },
  {
    title: 'ПредПрофи. Дизайн. Худграф.',
    description:
      'Продвинутый уровень для тех, кто хочет отточить мастерство и собрать портфолио для поступления на направления: дизайн, худграф.',
    age: 14,
    audience: ['adults', 'applicants'],
    price: 6900,
    priceNote: 'длительность - 3 месяца',
    tone: 'lavender',
    icon: '/icons/picture.svg',
    image: '',
    href: '#',
  },
  {
    title: 'Композиция с нуля',
    description: 'Основные законы создания картины, построение перспективы — без художественного опыта.',
    age: 9,
    audience: ['beginners', 'kids'],
    price: 4900,
    priceNote: 'длительность - 1 месяц',
    tone: 'cream',
    icon: '/icons/gallery.svg',
    image: '',
    href: '#',
  },
  {
    title: 'Сказочный мир',
    description: 'Набор работ по композиции с сюжетами популярных сказок: от замка доброй феи, до золушки.',
    age: 6,
    audience: ['kids', 'beginners'],
    price: 3500,
    priceNote: 'за месяц',
    tone: 'lavender',
    icon: '/icons/message.svg',
    image: '',
    href: '#',
  },
  {
    title: 'Мастер акварелист',
    description:
      'Работы в технике акварель - пошаговое продвижение к продвинутому уровню живописи. Для тех, кто уже знаком с основами живописи.',
    age: 14,
    audience: ['adults'],
    price: 6900,
    priceNote: 'за курс',
    tone: 'peach',
    icon: '/icons/nav.svg',
    image: '',
    href: '#',
  },
  {
    title: 'Живопись с нуля',
    description:
      'Основы цветоведения, материалы, приемы живописи, лепка формы цветом объемных предметов. Передача фактуры материала.',
    age: 9,
    audience: ['beginners', 'kids'],
    price: 4900,
    priceNote: 'за месяц',
    tone: 'lavender',
    icon: '/icons/brush.svg',
    image: '',
    href: '#',
  },
  {
    title: 'Основы изобразительной грамоты',
    description: 'Графика, рисунок животных, натюрморт из трех предметов и более, разноплановый пейзаж, основы дизайна.',
    age: 10,
    audience: ['kids', 'beginners'],
    price: 6500,
    priceNote: 'за месяц',
    tone: 'peach',
    icon: '/icons/point.svg',
    image: '',
    href: '#',
  },
  {
    title: 'Мастер в технике гуашь',
    description:
      'Работы в технике гуашь - пошаговое продвижение к продвинутому уровню живописи. Для тех, кто уже знаком с основами живописи.',
    age: 14,
    audience: ['adults'],
    price: 6900,
    priceNote: 'за месяц',
    tone: 'cream',
    icon: '/icons/picture.svg',
    image: '',
    href: '#',
  },
  {
    title: 'Дизайн с нуля',
    description:
      'Статика и динамика, большое/малое пятно, стилизация объектов, шрифты, словообраз — без художественного опыта.',
    age: 9,
    audience: ['beginners', 'kids'],
    price: 4900,
    priceNote: 'за месяц',
    tone: 'lavender',
    icon: '/icons/brush.svg',
    image: '',
    href: '#',
  },
  {
    title: 'На пути к мастеру',
    description: 'Тематические натюрморты по рисунку, живописи. Композиции конкурсного уровня.',
    age: 12,
    audience: ['kids', 'beginners'],
    price: 8500,
    priceNote: 'за месяц',
    tone: 'peach',
    icon: '/icons/point.svg',
    image: '',
    href: '#',
  },
  {
    title: 'График-Профи',
    description: 'Работы в технике карандаш, соус, уголь, тушь, перо. Для тех, кто уже знаком с основами рисунка.',
    age: 14,
    audience: ['adults'],
    price: 6900,
    priceNote: 'за месяц',
    tone: 'cream',
    icon: '/icons/picture.svg',
    image: '',
    href: '#',
  },
  {
    title: 'Скульптура',
    description: 'Материаловедение, передача формы, фактуры, детализация — без художественного опыта.',
    age: 9,
    audience: ['beginners', 'kids'],
    price: 4900,
    priceNote: 'за месяц',
    tone: 'lavender',
    icon: '/icons/brush.svg',
    image: '',
    href: '#',
  },
];
